#pragma once

extern HDC ghdc;

#define MYICON 101

#define ID_MUSIC 200

#define MY_BITMAP_LOGO 201
#define MY_BITMAP_FLAME 202
#define MY_BITMAP_TREE 203

#define MY_SACK_TEXTURE 205
#define MY_CARDS_TEXTURE 206

#define MY_SAD_FACE_BITMAP 211
#define WHITE_CLOTH_BITMAP 212
#define UPPER_WEAR_BITMAP 213
#define MY_EVIL_SMILE_FACE_BITMAP 214

#define MY_EARTH_BITMAP 215
#define MY_SPACE_BITMAP 217

// for terrain 
#define MY_BITMAP_MOUNTAIN 300
#define MY_BITMAP_CLOUD 301
#define MY_BITMAP_LANDSCAPE 302
#define MY_BITMAP_GRASS 303
#define MY_BITMAP_WHITE_CLOUD_SKY 304

// for temple
#define MY_STONE_BITMAP 400
#define MY_ROPE_BITMAP 401
#define MY_GOLD_BITMAP 402
#define MY_MARBLE_BITMAP 403
#define MY_WALL_1_BITMAP 404
#define MY_WALL_2_BITMAP 405
#define MY_SHREEVISHNU_1_BITMAP 406
#define MY_SHREEGANESH_BITMAP 407
#define MY_INVERTEDTREE 408
#define MY_TRIPUNDBITMAP 409
#define MY_BLACKBITMAP 410
#define MY_SKIN_TEXTURE 412

// for farm
#define MY_SOIL_BITMAP 510
#define MY_PLANT_BITMAP 511
#define MY_BAZARI_BITMAP 512
#define MY_WHITE_CLOTH_BITMAP 513
#define MY_DRY_GRASS_BITMAP 514
#define MY_FACE_BITMAP 515
#define MY_WALL_TEXTURE_BITMAP 516
#define MY_DOOR_TEXTURE_BITMAP 517
#define MY_WALL1_TEXTURE_BITMAP 518
#define MY_TOPCEILING_TEXTURE_BITMAP 519
#define MY_ROCK_WALL_TEXTURE_BITMAP 520


